### ISSUE TITLE
[SCM Integrations] New line is not interpreted in integrations-delete command

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/cli#766] opened 2022-08-12 15:23 UTC
```
$ scalingo -a test integrations-delete gitlab
 !     400 Bad Request → integration is still used by application repo links:
- Region 'local': Application 'test'\n- Region 'local': Application 'test-2'
```

**Comment by EtienneM** [comment] 2022-08-20 08:08
Seems like a similar error as https://github.com/Scalingo/cli/issues/743 fixed in https://github.com/Scalingo/cli/pull/744

**Comment by Soulou** [comment] 2022-09-06 08:41
Duplicate of https://github.com/Scalingo/cli/issues/743

**Closed by Soulou** 2022-09-06 08:41 UTC
Labels: quicky, good first issue, IST, low
