### ISSUE TITLE
Command fails with "The application was not found" when two spaces precedes the command

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [Scalingo/cli#972] opened 2023-06-14 08:34 UTC
```
$ scalingo -a test ps
+-------+---------+---------+------+---------------------+
| NAME  | STATUS  | COMMAND | SIZE |     CREATED AT      |
+-------+---------+---------+------+---------------------+
| web-1 | running |         | M    | 2023/04/05 15:40:05 |
+-------+---------+---------+------+---------------------+
$ scalingo -a test  ps
!     The application was not found on the region osc-fr1.
```

Please note that it has been identified on a Mac.
I was not able to reproduce on Linux.

**Comment by EtienneM** [comment] 2023-06-14 09:19
Customer used MacOS 10.15.7. This version is no longer supported by Apple since Septembre 2022. 

We fail to reproduce the bug on more recent version of MacOS and on Linux. Hence I would be in favor of closing this issue as won't fix.

**Closed** 2023-06-14 10:15 UTC
Labels: low
