### ISSUE TITLE
[one-off] There should be a way to stop a one-off container

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#404] opened 2019-03-22 15:15 UTC

**Comment by EtienneM** [comment] 2019-03-22 15:18
Isn't it a duplicate of #315 ?

**Comment by Soulou** [comment] 2019-03-22 15:19
Hmmm I don't know, it's related but not duplicate, just have a look at the example of #315, I'm renaming this issue `to stop a one-off container`

**Comment by yanjost** [comment] 2019-03-22 17:53
a one-off container should be killed when the connection with the client is broken, don't you think ?

**Comment by johnsudaar** [comment] 2020-06-05 12:39
@yanjost Yes this is the case. But you can also run detached one-off, in this case there is no connection between the container and the client.

UP !

**Comment by yanjost** [comment] 2020-06-05 16:27
How does the customer know a one-off container is running then ?

**Comment by johnsudaar** [comment] 2020-06-05 19:24
`scalingo -a MYAPP stats`

**Comment by Soulou** [comment] 2020-06-05 20:07
Which is crappy, they should be visible with `ps`

**Comment by yanjost** [comment] 2020-06-10 10:42
They should even be visible in the application dashboard

**Closed** 2021-03-31 07:42 UTC
